language: php
php:
  - 5.6
  - 7.0

sudo: false

cache:
   directories:
     - $HOME/.composer/cache/files

env:
  - SHOPWARE_VERSION: 5.2
  - SHOPWARE_VERSION: 5.3

matrix:
  allow_failures:
    - env: SHOPWARE_VERSION=5.3

before_script:
    - git clone https://github.com/shopware/shopware.git /tmp/shopware
    - cd /tmp/shopware
    - git checkout $SHOPWARE_VERSION

    - mv /home/travis/build/shopware/SwagConnect /tmp/shopware/engine/Shopware/Plugins/Local/Backend/SwagConnect
    - cd /tmp/shopware/engine/Shopware/Plugins/Local/Backend/SwagConnect
    - mkdir -p build/logs
    - composer install
    - cd vendor/shopware/plugin-dev-tools
    - ls
    - ls config
    - ./install.sh
    - cd /tmp/shopware/engine/Shopware/Plugins/Local/Backend/SwagConnect
    - ln -s vendor/shopware/plugin-dev-tools/psh56.phar psh56
    - ./psh56 travis:init

script: ./psh56 travis:unit-coveralls

notifications:
    email: false

after_success:
  - travis_retry ./psh56 travis:send-coverall-report